### ISSUE TITLE
Request: Add information

### ISSUE THREAD

**Issue by horseDeveloper** [thiswillbeyourgithub/LogseqPDFImporter#8]
Hey I was reading one of your posts and it looks like this script was developed using Okular as a base for the annotations. Would you mind putting this info into the readme? Even better, you could make a small section where we list when the software works (✅ Okular). I'm going to use your script in the future and I don't want to forget this ahahah

**Comment by thiswillbeyourgithub** [comment]
This is done. Thanks

**Comment by thiswillbeyourgithub** [comment]
It was not developped using Okular, it's just what I've been using as well as Xodo on android. I assume it works out of the box on most pdf readers. The quirks that might pose an issue are not expected anyway because logseq itself couldn't handle them. Things like elliptical areas, free hand drawing etc.
